// <auto-generated />
using System;
using CalorieBurnMgt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieBurnMgt.Migrations
{
    [DbContext(typeof(CalorieBurnDbContext))]
    [Migration("20251121010252_PutTotalCalorieBalanceInUsers")]
    partial class PutTotalCalorieBalanceInUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieBurnMgt.Models.Calorie", b =>
                {
                    b.Property<int>("CalorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalorieId"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<int>("CaloriesTaken")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBurned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateConsumed")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistanceTaken")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CalorieId");

                    b.HasIndex("UserId");

                    b.ToTable("Calories");
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Calories = 95,
                            Name = "Apple (medium)"
                        },
                        new
                        {
                            FoodId = 2,
                            Calories = 105,
                            Name = "Banana (medium)"
                        },
                        new
                        {
                            FoodId = 3,
                            Calories = 80,
                            Name = "White bread (slice)"
                        },
                        new
                        {
                            FoodId = 4,
                            Calories = 215,
                            Name = "Brown rice (cooked, 1 cup)"
                        },
                        new
                        {
                            FoodId = 5,
                            Calories = 165,
                            Name = "Chicken breast (grilled, skinless, 100g)"
                        },
                        new
                        {
                            FoodId = 6,
                            Calories = 206,
                            Name = "Salmon (cooked, 100g)"
                        },
                        new
                        {
                            FoodId = 7,
                            Calories = 78,
                            Name = "Egg (large, boiled)"
                        },
                        new
                        {
                            FoodId = 8,
                            Calories = 164,
                            Name = "Almonds (raw, 28g)"
                        },
                        new
                        {
                            FoodId = 9,
                            Calories = 322,
                            Name = "Avocado (medium)"
                        },
                        new
                        {
                            FoodId = 10,
                            Calories = 31,
                            Name = "Broccoli (raw, 1 cup)"
                        },
                        new
                        {
                            FoodId = 11,
                            Calories = 25,
                            Name = "Carrot (medium)"
                        },
                        new
                        {
                            FoodId = 12,
                            Calories = 113,
                            Name = "Cheddar cheese (28g)"
                        },
                        new
                        {
                            FoodId = 13,
                            Calories = 149,
                            Name = "Whole milk (1 cup)"
                        },
                        new
                        {
                            FoodId = 14,
                            Calories = 73,
                            Name = "Greek yogurt (plain, low-fat, 100g)"
                        },
                        new
                        {
                            FoodId = 15,
                            Calories = 161,
                            Name = "Potato (baked, medium)"
                        },
                        new
                        {
                            FoodId = 16,
                            Calories = 271,
                            Name = "Beef steak (grilled, lean, 100g)"
                        },
                        new
                        {
                            FoodId = 17,
                            Calories = 221,
                            Name = "Pasta (cooked spaghetti, 1 cup)"
                        },
                        new
                        {
                            FoodId = 18,
                            Calories = 166,
                            Name = "Oatmeal (cooked, 1 cup)"
                        },
                        new
                        {
                            FoodId = 19,
                            Calories = 62,
                            Name = "Orange (medium)"
                        },
                        new
                        {
                            FoodId = 20,
                            Calories = 46,
                            Name = "Strawberries (1 cup)"
                        });
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.Calorie", b =>
                {
                    b.HasOne("CalorieBurnMgt.Models.User", null)
                        .WithMany("Calories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.User", b =>
                {
                    b.Navigation("Calories");
                });
#pragma warning restore 612, 618
        }
    }
}
