// <auto-generated />
using System;
using CalorieBurnMgt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieBurnMgt.Migrations
{
    [DbContext(typeof(CalorieBurnDbContext))]
    partial class CalorieBurnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieBurnMgt.Models.Calorie", b =>
                {
                    b.Property<int>("CalorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalorieId"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<int>("CaloriesTaken")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBurned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateConsumed")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CalorieId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Calories");
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.Calorie", b =>
                {
                    b.HasOne("CalorieBurnMgt.Models.User", null)
                        .WithOne("Calorie")
                        .HasForeignKey("CalorieBurnMgt.Models.Calorie", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieBurnMgt.Models.User", b =>
                {
                    b.Navigation("Calorie")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
